////////////////////////////////////////////////////////////////
//                                                            //
//  DO NOT EDIT THIS FILE -- WRITE YOUR FUNCTIONS IN  tp5.c   //
//                                                            //
////////////////////////////////////////////////////////////////

// Reads the contents of "tp5.c", ignoring any main() function,
#define main no__main
#include "tp5.c"
#undef main

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <errno.h>
#include <inttypes.h>
#include <assert.h>

struct xx_ranctx { uint32_t a; uint32_t b; uint32_t c; uint32_t d; } xx_ranc;

uint32_t xx_ranval()
{
#define rot(x, k) (((x) << (k)) | ((x) >> (32 - (k))))
  uint32_t e = xx_ranc.a - rot(xx_ranc.b, 27);
  xx_ranc.a = xx_ranc.b ^ rot(xx_ranc.c, 17);
  xx_ranc.b = xx_ranc.c + xx_ranc.d;
  xx_ranc.c = xx_ranc.d + e;
  xx_ranc.d = e + xx_ranc.a;
  return xx_ranc.d;
}

void xx_raninit(uint32_t seed)
{
  xx_ranc.a = 0xf1ea5eed, xx_ranc.b = xx_ranc.c = xx_ranc.d = seed;
  for (uint32_t i = 0; i < 20; ++i)
    (void) xx_ranval();
}

void xx_fisher_yates_shuffle(unsigned* tab, unsigned count)
{
  unsigned i = count;
  while (i)
    {
      unsigned j = xx_ranval() % i--;
      unsigned tmp = tab[i];
      tab[i] = tab[j];
      tab[j] = tmp;
    }
}

FILE* xx_trace;
const char* xx_trace_name;

void xx_trace_init(const char* name)
{
  xx_trace_name = getenv("OUTPUT");
  if (!xx_trace_name)
    {
      static char tmp[30];
      strncpy(tmp, name, 23);
      strcat(tmp, ".trace");
      xx_trace_name = tmp;
    }
  xx_trace = fopen(xx_trace_name, "w+");
  if (!xx_trace)
    {
      fprintf(stderr, "cannot open '%s' for writing: %s\n",
	      xx_trace_name, strerror(errno));
      exit(2);
    }

  time_t rawtime = time(NULL);
  struct tm *timeinfo = gmtime(&rawtime);
  char buffer[20];
  strftime(buffer, 80, "%F %T%n", timeinfo);

  int u = getuid();
  int r = rawtime & 0xffffff;
  fprintf(xx_trace, "%s\n%d\n%d\n", name, u, r);
  fputs(buffer, xx_trace);
  u ^= r;
  const char* s = getenv("SEED");
  if (s)
    u = atoi(s);
  xx_raninit(u);
}

void xx_trace_done()
{
  fclose(xx_trace);
  printf("please submit '%s'\n", xx_trace_name);
}

int xx_cmp(int a, int b)
{
  if (((a&1) == 0) && ((b&1) == 1))
    return -1;
  if (((a&1) == 1) && ((b&1) == 0))
    return 1;
  if (a < b)
    return -1;
  return a > b;
}

int main()
{
#if Q == 3
  xx_trace_init("tp5q3");
  const unsigned asize = 2*1024*1024;
  int* a = malloc(asize * sizeof(int));
  unsigned val = 0;
  for (unsigned i = 0; i < asize; ++i)
    a[i] = val += 1 + (xx_ranval() % 4);
  heap_sort_cmp(a, asize, xx_cmp);
  fprintf(xx_trace, "after heap_sort, head:\n");
  print_int_array(xx_trace, a, 60);
  fprintf(xx_trace, "after heap_sort, tail:\n");
  print_int_array(xx_trace, a + asize - 60, 60);
  int* b = malloc(asize * sizeof(int));
  const unsigned k = asize / 2;
  for (unsigned i = 1; i <= k; ++i)
    {
      b[i - 1] = a[(i & 1) ? i - 1: k + i - 2];
      b[k + i - 1] = a[2 * i - 1];
    }
  free(a);
  intro_sort_cmp(b, asize, xx_cmp);
  fprintf(xx_trace, "after intro_sort, head:\n");
  print_int_array(xx_trace, b, 60);
  fprintf(xx_trace, "after intro_sort, mid:\n");
  print_int_array(xx_trace, b + asize/2 - 30, 60);
  fprintf(xx_trace, "after intro_sort, tail:\n");
  print_int_array(xx_trace, b + asize - 60, 60);
  xx_trace_done();
  free(b);
#elif Q == 5
  xx_trace_init("tp5q5");
  const unsigned csize = 5 + (xx_ranval() % 2);
  unsigned int coins[csize];
  unsigned val = 1;
  for (unsigned i = 0; i < csize; ++i)
    {
      coins[i] = val;
      val += 1 + (xx_ranval() % 5);
    }
  xx_fisher_yates_shuffle(coins, csize);
  fputs("coins:", xx_trace);
  for (unsigned i = 0; i < csize; ++i)
    fprintf(xx_trace, " %d", coins[i]);
  fputc('\n', xx_trace);
  for (unsigned i = 0; i < 10; ++i)
    {
      unsigned amount = 300 + (xx_ranval() % 350);
      fprintf(xx_trace, "combo(..., %u) == %u\n", amount,
	      coin_combo(coins, csize, amount));
    }
  xx_trace_done();
#else
  puts("Compile with -DQ=n, where n is the question number.");
#endif
  return 0;
}
